require("mauriceelliott.remap")
require("mauriceelliott.packer")
require("mauriceelliott.settings")
require("mauriceelliott.lualine")
require("mauriceelliott.cyberdream")
require("mauriceelliott.lsp")
